name: cityclean
description: "la tua app per l'ambiente"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# ⬇⬇⬇ ATTENZIONE: questa sezione deve stare FUORI da "flutter:" ⬇⬇⬇
flutter_native_splash:
  color: "#A7FFB5"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#A7FFB5"
    image: assets/images/logo.png
