name: cityclean
description: "la tua app per l'ambiente"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.3
  tflite_flutter: ^0.12.1 # Libreria per la classificazione
  image: ^4.2.0          # Per processare le immagini
  camera: ^0.11.1
  fl_chart: ^0.68.0      # Aggiunto per i grafici

  http: any
  provider: ^6.1.5+1

  # Dipendenze aggiunte per la sezione Admin
  csv: ^5.1.1
  path_provider: ^2.1.3
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1 # <-- AGGIUNTA

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
    - .env


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#A7FFB5"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#A7FFB5"
    image: assets/images/logo.png
