name: CityClean CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create dummy .env file
        run: |
          touch .env
          echo "SUPABASE_URL=https://fake.supabase.co" >> .env
          echo "SUPABASE_ANON_KEY=fake_key" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build APK (Dry Run)
        run: flutter build apk --debug